[workspace]
members = [
    "crates/cef-rs-osr-sample",
    "crates/cef-rs-sample",
    "crates/cef-rs-sample-bundle-macos",
    "crates/cef-rs-sample-helper",
    "crates/mini-browser",
]
resolver = "3"

[workspace.dependencies]
cef = "141.6.0"
